# Generated by Django 5.1.9 on 2025-10-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資料名稱')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('file_path', models.FileField(upload_to='uploads/', verbose_name='檔案路徑')),
            ],
        ),
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(default='line', max_length=50, verbose_name='圖表類型')),
                ('x_axis', models.CharField(max_length=50, verbose_name='X軸欄位')),
                ('y_axis', models.CharField(max_length=200, verbose_name='Y軸欄位（多選）')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='顏色')),
                ('line_style', models.CharField(default='solid', max_length=20, verbose_name='線條樣式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dataviz.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_json', models.JSONField(verbose_name='摘要統計（JSON）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dataviz.dataset')),
            ],
        ),
    ]
