# Generated by Django 5.1.9 on 2025-12-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treedoc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeversion',
            name='content',
        ),
        migrations.AddField(
            model_name='treeversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='treedoc_files/%Y/%m/%d/'),
        ),
    ]
