# Generated by Django 5.1.9 on 2025-12-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treedoc', '0002_remove_treeversion_content_treeversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeversion',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treeversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='treedoc_files/'),
        ),
    ]
