# Generated by Django 5.1.9 on 2025-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='tasks/'),
        ),
    ]
