# Generated by Django 5.1.9 on 2025-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件標題')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('color', models.CharField(default='#93c5fd', help_text='由使用者從固定色票挑選（8 色）', max_length=20, verbose_name='顏色代碼')),
                ('tag', models.CharField(blank=True, help_text='例如：學業、運動、生活', max_length=50, verbose_name='分類標籤')),
                ('priority', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=10, verbose_name='優先順序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '個人事件',
                'verbose_name_plural': '個人行事曆事件',
                'ordering': ['start'],
            },
        ),
    ]
