# Generated by Django 5.1.9 on 2025-11-09 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('color', models.CharField(default='#60A5FA', max_length=20, verbose_name='顏色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
