# Generated by Django 5.1.9 on 2025-11-10 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_event_description_event_note_event_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start'], 'verbose_name': '個人事件', 'verbose_name_plural': '個人行事曆事件'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#93c5fd', help_text='由使用者從固定色票挑選（8 色）', max_length=20, verbose_name='顏色代碼'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=10, verbose_name='優先順序'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, help_text='例如：學業、運動、生活', max_length=50, verbose_name='分類標籤'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='事件標題'),
        ),
    ]
